var GAME_STATE = {
	WAITING: 'WAITING',
	PLAYING: 'PLAYING',
	FAIL: 'FAIL',
};

var VECTORS = {
	CENTER: 'CENTER',
	LEFT: 'LEFT',
	RIGHT: 'RIGHT',
};

var ROOMS = {
	TOP_LEFT     : 'TOP_LEFT',
	TOP_CENTER   : 'TOP_CENTER',
	TOP_RIGHT    : 'TOP_RIGHT',
	BOTTOM_LEFT  : 'BOTTOM_LEFT',
	BOTTOM_CENTER: 'BOTTOM_CENTER',
	BOTTOM_RIGHT : 'BOTTOM_RIGHT',
};

var VECTORS = {
	CENTER: 'CENTER',
	LEFT: 'LEFT',
	RIGHT: 'RIGHT',
};

var ROOM_TO_VECTOR = {
	TOP_LEFT     : VECTORS.LEFT,
	TOP_CENTER   : VECTORS.CENTER,
	TOP_RIGHT    : VECTORS.RIGHT,
	BOTTOM_LEFT  : VECTORS.LEFT,
	BOTTOM_CENTER: VECTORS.CENTER,
	BOTTOM_RIGHT : VECTORS.RIGHT,
};

module.exports = {
	GAME_STATE    : GAME_STATE,
	ROOM_TO_VECTOR: ROOM_TO_VECTOR,
	ROOMS         : ROOMS,
	VECTORS       : VECTORS,
}